# DataFrame shapes for table extractor verification

This notebook creates various pandas DataFrame configurations to verify `extractTableFromHTML` correctly parses pandas `_repr_html_` output.

Run each cell and compare the displayed table with Orion's rendered output.

In [1]:
import pandas as pd

## 1. Simple single-index (default integer index, no names)

In [2]:
df1 = pd.DataFrame({"A": [1, 2], "B": [3, 4]})
df1

   A  B
0  1  3
1  2  4

## 2. Named index, unnamed columns

In [3]:
df2 = pd.DataFrame({"A": [1, 2], "B": [3, 4]}, index=["x", "y"])
df2.index.name = "my_index"
df2

          A  B
my_index
x         1  3
y         2  4

## 3. Unnamed index, named columns

In [4]:
df3 = pd.DataFrame({"A": [1, 2], "B": [3, 4]})
df3.columns.name = "my_cols"
df3

my_cols  A  B
0        1  3
1        2  4

## 4. Named index AND named columns (bug case — 2-row thead)

In [16]:
df4 = pd.DataFrame({"A": [1, 2], "B": [3, 4]}, index=["x", "y"])
df4.index.name = "my_index"
df4.columns.name = "my_cols"
df4

my_cols   A  B
my_index
x         1  3
y         2  4

## 5. Multi-index columns, single row index

In [6]:
df5 = pd.DataFrame(
    [[1, 2, 3, 4], [5, 6, 7, 8]],
    columns=pd.MultiIndex.from_tuples([("A", "one"), ("A", "two"), ("B", "one"), ("B", "two")]),
)
df5

    A       B
  one two one two
0   1   2   3   4
1   5   6   7   8

## 6. Multi-index rows (unnamed levels)

In [7]:
df6 = pd.DataFrame(
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    index=pd.MultiIndex.from_tuples([("bar", "one"), ("bar", "two"), ("baz", "one")]),
    columns=pd.MultiIndex.from_tuples([("A", "x"), ("A", "y"), ("B", "x")]),
)
df6

         A     B
         x  y  x
bar one  1  2  3
    two  4  5  6
baz one  7  8  9

## 7. Named multi-index rows

In [8]:
df7 = pd.DataFrame(
    [[100, 200], [110, 210], [300, 400]],
    index=pd.MultiIndex.from_tuples(
        [("US", "2020"), ("US", "2021"), ("EU", "2020")],
        names=["Region", "Year"],
    ),
    columns=["val1", "val2"],
)
df7

             val1  val2
Region Year
US     2020   100   200
       2021   110   210
EU     2020   300   400

## 8. No index (index=False)

In [9]:
df8 = pd.DataFrame({"A": [1, 4], "B": [2, 5], "C": [3, 6]})
df8

   A  B  C
0  1  2  3
1  4  5  6

In [10]:
# Display without index (use to_html for raw HTML)
from IPython.display import HTML
HTML(df8.to_html(index=False))

## 9. Three-level column MultiIndex

In [11]:
df9 = pd.DataFrame(
    [[1, 2, 3, 4]],
    columns=pd.MultiIndex.from_tuples(
        [("A", "x", "i"), ("A", "x", "ii"), ("A", "y", "i"), ("B", "x", "i")]
    ),
)
df9

   A        B
   x     y  x
   i ii  i  i
0  1  2  3  4

## 10. Raw HTML snippets for extractTableFromHTML

In [21]:
# Print _repr_html_ for each DataFrame (for copy-paste into tests)
for name, html in [
    ("df1", df1._repr_html_()),
    ("df2", df2._repr_html_()),
    ("df3", df3._repr_html_()),
    ("df4", df4._repr_html_()),
    ("df5", df5._repr_html_()),
    ("df6", df6._repr_html_()),
    ("df7", df7._repr_html_()),
    ("df8 (no index)", df8.to_html(index=False)),
    ("df9", df9._repr_html_()),
]:
    print(f"\n=== {name} ===")
    print(html)

=== df1 ===
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>A</th>
      <th>B</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>3</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2</td>
      <td>4</td>
    </tr>
  </tbody>
</table>
</div>

=== df2 ===
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>A</th>
      <th>B</th>
    </tr>
    <tr>
      <th>my_index</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>x</th>
      <td>1</td>
      <td>3</td>
    </tr>
    <tr>
      <th>y</th>
      <td>2</td>
      <td>4</td>
    </tr>
  </tbody>
</table>
</div>

=== df3 ===
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>my_cols</th>
      <th>A</th>
      <th>B</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>3</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2</td>
      <td>4</td>
    </tr>
  </tbody>
</table>
</div>

=== df4 ===
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>my_cols</th>
      <th>A</th>
      <th>B</th>
    </tr>
    <tr>
      <th>my_index</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>x</th>
      <td>1</td>
      <td>3</td>
    </tr>
    <tr>
      <th>y</th>
      <td>2</td>
      <td>4</td>
    </tr>
  </tbody>
</table>
</div>

=== df5 ===
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead tr th {
        text-align: left;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr>
      <th></th>
      <th colspan="2" halign="left">A</th>
      <th colspan="2" halign="left">B</th>
    </tr>
    <tr>
      <th></th>
      <th>one</th>
      <th>two</th>
      <th>one</th>
      <th>two</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>2</td>
      <td>3</td>
      <td>4</td>
    </tr>
    <tr>
      <th>1</th>
      <td>5</td>
      <td>6</td>
      <td>7</td>
      <td>8</td>
    </tr>
  </tbody>
</table>
</div>

=== df6 ===
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead tr th {
        text-align: left;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th colspan="2" halign="left">A</th>
      <th>B</th>
    </tr>
    <tr>
      <th></th>
      <th></th>
      <th>x</th>
      <th>y</th>
      <th>x</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="2" valign="top">bar</th>
      <th>one</th>
      <td>1</td>
      <td>2</td>
      <td>3</td>
    </tr>
    <tr>
      <th>two</th>
      <td>4</td>
      <td>5</td>
      <td>6</td>
    </tr>
    <tr>
      <th>baz</th>
      <th>one</th>
      <td>7</td>
      <td>8</td>
      <td>9</td>
    </tr>
  </tbody>
</table>
</div>

=== df7 ===
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th></th>
      <th>val1</th>
      <th>val2</th>
    </tr>
    <tr>
      <th>Region</th>
      <th>Year</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="2" valign="top">US</th>
      <th>2020</th>
      <td>100</td>
      <td>200</td>
    </tr>
    <tr>
      <th>2021</th>
      <td>110</td>
      <td>210</td>
    </tr>
    <tr>
      <th>EU</th>
      <th>2020</th>
      <td>300</td>
      <td>400</td>
    </tr>
  </tbody>
</table>
</div>

=== df8 (no index) ===
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>A</th>
      <th>B</th>
      <th>C</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td>
      <td>2</td>
      <td>3</td>
    </tr>
    <tr>
      <td>4</td>
      <td>5</td>
      <td>6</td>
    </tr>
  </tbody>
</table>

=== df9 ===
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead tr th {
        text-align: left;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr>
      <th></th>
      <th colspan="3" halign="left">A</th>
      <th>B</th>
    </tr>
    <tr>
      <th></th>
      <th colspan="2" halign="left">x</th>
      <th>y</th>
      <th>x</th>
    </tr>
    <tr>
      <th></th>
      <th>i</th>
      <th>ii</th>
      <th>i</th>
      <th>i</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>2</td>
      <td>3</td>
      <td>4</td>
    </tr>
  </tbody>
</table>
</div>